---
name: "Pull Request Labeler"
on: pull_request_target
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          sync-labels: ''
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
